name: Deploy

on:
  schedule:
    - cron: "0 16 * * *" # 01:00(JST)
  workflow_dispatch:

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    env:
      NOTION_API_SECRET: ${{ secrets.NOTION_API_SECRET }}
      DATA_SOURCE_ID: ${{ secrets.DATA_SOURCE_ID }}
      DATABASE_ID: ${{ secrets.DATABASE_ID }}
      CUSTOM_DOMAIN: ${{ secrets.CUSTOM_DOMAIN }}
      PUBLIC_GA_TRACKING_ID: ${{ secrets.PUBLIC_GA_TRACKING_ID }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
      - name: Deploy to server
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          server: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USER }}
          port: ${{ secrets.SFTP_PORT }}
          local_path: "./dist/*"
          remote_path: ${{ secrets.SFTP_REMOTE_PATH }}
